[package]
name = "futures-util-preview"
edition = "2018"
version = "0.3.0-alpha.16"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-lang-nursery/futures-rs"
homepage = "https://rust-lang-nursery.github.io/futures-rs"
documentation = "https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.16/futures_util"
description = """
Common utilities and extension traits for the futures-rs library.
"""

[lib]
name = "futures_util"

[features]
std = ["alloc_feature", "futures-core-preview/std", "futures-io-preview/std", "futures-sink-preview/std", "slab", "memchr"]
default = ["std"]
async-await = ["std", "futures-select-macro-preview", "proc-macro-hack", "proc-macro-nested", "rand", "rand_core"]
compat = ["std", "futures_01"]
io-compat = ["compat", "tokio-io"]
bench = []
nightly = ["futures-core-preview/nightly", "futures-sink-preview/nightly"]
cfg-target-has-atomic = ["futures-core-preview/cfg-target-has-atomic"]
never-type = []
alloc_feature  = ["futures-core-preview/alloc_feature", "futures-sink-preview/alloc_feature"]

# For std building
rustc-internal-api = []
rustc-dep-of-std = ["core", "compiler_builtins", "alloc", "rustc-internal-api",
                    "futures-core-preview/rustc-dep-of-std",
                    "futures-channel-preview/rustc-dep-of-std",
                    "futures-io-preview/rustc-dep-of-std",
                    "futures-sink-preview/rustc-dep-of-std",
                    ]

[dependencies]
futures-core-preview = { path = "../futures-core", version = "=0.3.0-alpha.16", default-features = false }
futures-channel-preview = { path = "../futures-channel", version = "=0.3.0-alpha.16", default-features = false }
futures-io-preview = { path = "../futures-io", version = "=0.3.0-alpha.16", default-features = false }
futures-sink-preview = { path = "../futures-sink", version = "=0.3.0-alpha.16", default-features = false}
futures-select-macro-preview = { path = "../futures-select-macro", version = "=0.3.0-alpha.16", default-features = false, optional = true }
proc-macro-hack = { version = "0.5", optional = true }
proc-macro-nested = { version = "0.1.2", optional = true }
rand = { version = "0.6.4", optional = true }
rand_core = { version = ">=0.2.2, <0.4", optional = true } # See https://github.com/rust-random/rand/issues/645
slab = { version = "0.4", optional = true }
memchr = { version = "2.2", optional = true }
futures_01 = { version = "0.1.25", optional = true, package = "futures" }
tokio-io = { version = "0.1.9", optional = true }
pin-utils = "0.1.0-alpha.4"

# When built as part of libstd
core = { version = "1.0.0", optional = true, package = "rustc-std-workspace-core" }
compiler_builtins = { version = "0.1.16", optional = true }
alloc = { version = "1.0.0", optional = true, package = "rustc-std-workspace-alloc" }

[dev-dependencies]
futures-preview = { path = "../futures", version = "=0.3.0-alpha.16", features = ["async-await", "nightly"] }
futures-executor-preview = { path = "../futures-executor", version = "=0.3.0-alpha.16" }
futures-test-preview = { path = "../futures-test", version = "=0.3.0-alpha.16" }
tokio = "0.1.11"
